#!/usr/bin/env python3
from packages.addcss import main as addcss
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Add CSS w/ Partitions')
    parser.add_argument('cluster', type=str)
    parser.add_argument('name', type=str)
    parser.add_argument('description', type=str)
    parser.add_argument('--n', dest='newName', type=str, help='CSS Name')
    parser.add_argument('--re', dest='members', nargs='+', help='CSS Members - Regex')
    parser.add_argument('--execute', action='store_true')
    args = parser.parse_args()
    addcss(args)

