#!/usr/bin/env python3
from packages.addpt import main as addpt
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Partition Adder')
    parser.add_argument('cluster', type=str)
    parser.add_argument('name', type=str)
    parser.add_argument('description', type=str)
    parser.add_argument('--execute', action='store_true')
    args = parser.parse_args()
    addpt(args)
