#!/usr/bin/env python3
from packages.updatept import main as updatept
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Bulk Partition Updater')
    parser.add_argument('cluster', type=str)
    parser.add_argument('pattern', type=str)
    parser.add_argument('match', type=str)
    parser.add_argument('replace', type=str)
    parser.add_argument('--execute', action='store_true')
    args = parser.parse_args()
    updatept(args)

