#!/usr/bin/env python3
from packages.updatecss import main as updatecss
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Bulk CSS Update')
    parser.add_argument('cluster', type=str)
    parser.add_argument('name', type=str)
    parser.add_argument('--re', dest='members', nargs='+', help='PT Members to Add')
    parser.add_argument('--execute', action='store_true')
    args = parser.parse_args()
    updatecss(args)
