#!/usr/bin/env python
import argparse
import re
import pprint
from packages.soap import SqlAddCss
from utilities import getPartitions, partitionFilter, flatten
from packages.generator import CssDesign, SpecificElement, GenericElement, LocSpecificElement

parser = argparse.ArgumentParser(description='Add CSS w/ Partitions')
parser.add_argument('name', type=str)
parser.add_argument('description', type=str)
parser.add_argument('--n', dest='newName', type=str, help='CSS Name')
parser.add_argument('--re', dest='members', nargs='+', help='CSS Members - Regex')
parser.add_argument('--execute', action='store_true') 
args = parser.parse_args()

pts = getPartitions()

partitionList = sorted(flatten([partitionFilter(pts, pattern) for pattern in args.members]))
pprint.pprint(partitionList)

if args.execute:
    print(SqlAddCss(args.name, args.description, partitionList).execute())
