#!/usr/bin/env python
import argparse
from packages.soap import SqlAddPartition

parser = argparse.ArgumentParser(description='Partition Adder')
parser.add_argument('ptName', type=str)
parser.add_argument('ptDescr', type=str)

args = parser.parse_args()

print(SqlAddPartition(args.ptName, args.ptDescr).execute())
