#!/usr/bin/env python
import argparse
import pprint
from utilities import getPartitions, ptSubstitute, partitionFilter
from packages.soap import SqlUpdatePt

parser = argparse.ArgumentParser(description='Bulk Partition Updater')
parser.add_argument('pattern', type=str)
parser.add_argument('match', type=str)
parser.add_argument('replace', type=str)
parser.add_argument("--execute", action='store_true')
args = parser.parse_args()

pts = getPartitions()
filteredPts = partitionFilter(pts, args.pattern)
ptDict = ptSubstitute(filteredPts, args.match, args.replace)

pprint.pprint(ptDict)

if args.execute:
    [print(SqlUpdatePt(oldName, newName).execute()) for oldName, newName in ptDict.items()]

